package com.ipl2019;

public enum IPLField
{
  AVERAGE,STRIKING_RATE,MAX_SIX_AND_FOURS,STRIKINRATE_MAX_SIX_AND_FOURS,MAX_STRIKINRATE_MAX_AVERAGE,MAX_RUNS_WITH_BEST_AVERAGE,ECONOMY,FOURWICKET,FIVEWICKET,STRIKING_RATE_FOURWKTS_FIVEWKTS;
}
